// Generated by tests/web/refresh.mjs from rent-halo-system 6471d01. Do not edit.
/* eslint-disable */
// @ts-nocheck
import { format, differenceInDays, max as dateMax, min as dateMin } from "date-fns";

function computeProRatedAmount(
  reservation: Reservation,
  periodStart: string,
  periodEnd: string
): { amount: number; days: number } {
  const resStart = new Date(reservation.check_in);
  const resEnd = new Date(reservation.check_out);
  const pStart = new Date(periodStart);
  const pEnd = new Date(periodEnd);

  const overlapStart = dateMax([resStart, pStart]);
  const overlapEnd = dateMin([resEnd, pEnd]);

  if (overlapStart >= overlapEnd) return { amount: 0, days: 0 };

  const totalDays = differenceInDays(resEnd, resStart);
  if (totalDays <= 0) return { amount: 0, days: 0 };

  const overlapDays = differenceInDays(overlapEnd, overlapStart);
  const dailyRate = reservation.total_price / totalDays;

  return {
    amount: Math.round(dailyRate * overlapDays * 100) / 100,
    days: overlapDays,
  };
}

/** The website Financial page's numbers, with its component state passed in. */
export function webFinancial({ reservations, apartments, financeRows, selectedApartments, manageFilter, startDate, endDate }) {
  const isAllSelected = selectedApartments.length === 0;
  const scopedApartments = manageFilter === "all" ? apartments : apartments.filter((a) => a.manage_type === manageFilter);
  const scopedIdSet = new Set(scopedApartments.map((a) => a.id));

    if (!startDate || !endDate) return null;

    const periodStart = format(startDate, "yyyy-MM-dd");
    const periodEnd = format(endDate, "yyyy-MM-dd");

    const filtered = reservations.filter((r) => {
      if (r.status === "cancelled") return false;
      if (!isAllSelected && !selectedApartments.includes(r.apartment_id)) return false;
      if (!scopedIdSet.has(r.apartment_id)) return false;

      // Check overlap
      return r.check_in < periodEnd && r.check_out > periodStart;
    });

    let totalAmount = 0;
    let totalCheckIns = 0;
    let bookedNights = 0;
    const bySource: Record<string, number> = { booking: 0, airbnb: 0, direct: 0 };
    const byDirectPayment: Record<string, number> = { cash: 0, payment_link: 0, bank_transfer: 0 };
    const breakdown: {
      reservation: Reservation;
      proRatedAmount: number;
      proRatedDays: number;
      isCheckIn: boolean;
    }[] = [];

    for (const res of filtered) {
      // Revenue counts in full from the selected period — including rent-free
      // grace periods before contract_start — but stops at contract_end
      // (exclusive) once a unit leaves management.
      const fin = financeRows.find((f) => f.apartment_id === res.apartment_id);
      const pStart = periodStart;
      let pEnd = periodEnd;
      if (fin?.contract_end && fin.contract_end < pEnd) pEnd = fin.contract_end;
      const { amount, days } = computeProRatedAmount(res, pStart, pEnd);
      bookedNights += days;
      if (amount <= 0) continue;

      const checkInDate = res.check_in;
      const isCheckIn = checkInDate >= periodStart && checkInDate < periodEnd;

      totalAmount += amount;
      if (isCheckIn) totalCheckIns++;
      bySource[res.source] = (bySource[res.source] || 0) + amount;
      if (res.source === "direct" && res.direct_payment_method) {
        byDirectPayment[res.direct_payment_method] = (byDirectPayment[res.direct_payment_method] || 0) + amount;
      }

      breakdown.push({
        reservation: res,
        proRatedAmount: amount,
        proRatedDays: days,
        isCheckIn,
      });
    }

    const periodDays = differenceInDays(endDate, startDate);
    const selectedIds = (isAllSelected ? apartments.map((a) => a.id) : selectedApartments).filter((id) => scopedIdSet.has(id));
    const listingCount = selectedIds.filter((id) => {
      const fin = financeRows.find((f) => f.apartment_id === id);
      const cEnd = fin?.contract_end ?? null;
      // Unit counts toward capacity until it leaves management (contract_end).
      // Grace periods before contract_start still count, matching revenue.
      return !cEnd || cEnd > periodStart;
    }).length;
    const capacity = periodDays * listingCount;
    const occupancy = capacity > 0 ? Math.min(100, (bookedNights / capacity) * 100) : 0;

    return { totalAmount, totalCheckIns, bySource, byDirectPayment, breakdown, occupancy, bookedNights, capacity };
}
