// Generated by tests/web/refresh.mjs from rent-halo-system 2fb1ffb. Do not edit.
/* eslint-disable */
// @ts-nocheck
export function guestCountsPayload(g: GuestCounts) {
  const n = (v: string) => Math.max(0, Math.floor(Number(v) || 0));
  return { adults: Math.max(1, n(g.adults)), children: n(g.children), infants: n(g.infants) };
}
