// Generated by tests/web/refresh.mjs from rent-halo-system 55c7750. Do not edit.
/* eslint-disable */
// @ts-nocheck
// Completes a mobile inspection; creates a pending task when damage is found.
import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders } from "../_shared/channex.ts";

// deno-lint-ignore no-explicit-any
type Any = any;
const json = (data: unknown, status = 200) =>
  new Response(JSON.stringify(data), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const token = (req.headers.get("Authorization") ?? "").replace("Bearer ", "");
  const { data: { user } } = await admin.auth.getUser(token);
  if (!user) return json({ error: "unauthorized" }, 401);
  const { data: roles } = await admin.from("user_roles").select("role").eq("user_id", user.id);
  if (!(roles ?? []).some((r: Any) => r.role === "admin" || r.role === "super_admin")) return json({ error: "forbidden" }, 403);

  let id: string | undefined;
  try { id = (await req.json())?.inspection_id; } catch { /* ignore */ }
  if (!id || typeof id !== "string") return json({ error: "inspection_id required" }, 400);

  const { data: insp } = await admin.from("mobile_inspections").select("*").eq("id", id).maybeSingle();
  if (!insp) return json({ error: "not found" }, 404);

  const bad = (Array.isArray(insp.results) ? insp.results : [])
    .filter((r: Any) => r?.condition === "damaged" || r?.condition === "missing");
  const damage = bad.length > 0;

  const { data: updated, error } = await admin.from("mobile_inspections")
    .update({ status: "completed", completed_at: new Date().toISOString(), damage_found: damage })
    .eq("id", id).select("*").single();
  if (error) return json({ error: error.message }, 500);

  if (damage) {
    const list = bad.map((r: Any) => `${r.room} – ${r.item} (${r.condition}${r.note ? `: ${r.note}` : ""})`).join("; ");
    const { error: tErr } = await admin.from("tasks").insert({
      user_id: user.id, apartment_id: insp.apartment_id, status: "pending",
      description: `Damage found during inspection: ${list}`,
    });
    if (tErr) console.error("task insert failed:", tErr);
  }
  return json(updated);
});
