// Generated by tests/web/refresh.mjs from rent-halo-system 55c7750. Do not edit.
/* eslint-disable */
// @ts-nocheck
// Mobile app push dispatcher. Runs every minute from pg_cron.
// A: guest-message notifications (same as channex-messages "threads"),
// B: create checkout inspections, C: send Expo pushes to admins.
import { createClient } from "npm:@supabase/supabase-js@2";
import { corsHeaders, channexFetch } from "../_shared/channex.ts";

// deno-lint-ignore no-explicit-any
type Any = any;

const json = (data: unknown, status = 200) =>
  new Response(JSON.stringify(data), { status, headers: { ...corsHeaders, "Content-Type": "application/json" } });

const dubaiDate = (d: Date = new Date()) =>
  new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Dubai", year: "numeric", month: "2-digit", day: "2-digit" }).format(d);

async function stepMessages(admin: Any) {
  const r = await channexFetch(admin, `/message_threads?pagination[page]=1&pagination[limit]=50`, "GET");
  if (!r.ok) throw new Error(`channex ${r.status}`);
  const rows: Any[] = (r.body as Any)?.data ?? [];

  const propIds = [...new Set(rows.map((t) => t.relationships?.property?.data?.id).filter(Boolean))];
  const unitByProp: Record<string, string> = {};
  if (propIds.length) {
    const { data: maps } = await admin.from("channex_mapping").select("channex_id, internal_id")
      .eq("entity_type", "property").in("channex_id", propIds);
    const internal = (maps ?? []).map((m: Any) => m.internal_id);
    if (internal.length) {
      const list = internal.join(",");
      const { data: apts } = await admin.from("apartments").select("id, name, room_type_id, buildings(name)")
        .or(`id.in.(${list}),room_type_id.in.(${list})`);
      for (const m of maps ?? []) {
        const names = (apts ?? []).filter((a: Any) => a.id === m.internal_id || a.room_type_id === m.internal_id)
          .map((a: Any) => (a.buildings?.name ? `${a.buildings.name} – ${a.name}` : a.name));
        if (names.length) unitByProp[m.channex_id] = names.length > 2 ? `${names.slice(0, 2).join(", ")} +${names.length - 2}` : names.join(", ");
      }
    }
  }

  const bookingIds = [...new Set(rows.map((t) => t.relationships?.booking?.data?.id).filter(Boolean))];
  const resByBooking: Record<string, Any> = {};
  if (bookingIds.length) {
    const { data: intake } = await admin.from("channex_booking_intake")
      .select("channex_booking_id, applied_reservation_id, received_at, raw_revision").in("channex_booking_id", bookingIds)
      .order("received_at", { ascending: false });
    const resCols = "id, guest_name, check_in, check_out, apartments(name, buildings(name))";
    const resIds = (intake ?? []).map((i: Any) => i.applied_reservation_id).filter(Boolean);
    if (resIds.length) {
      const { data: res } = await admin.from("reservations").select(resCols).in("id", resIds);
      for (const i of intake ?? []) {
        if (resByBooking[i.channex_booking_id]) continue;
        const rr = (res ?? []).find((x: Any) => x.id === i.applied_reservation_id);
        if (rr) resByBooking[i.channex_booking_id] = rr;
      }
    }
    const words = (s: string) => String(s ?? "").toLowerCase().split(/[^\p{L}]+/u).filter((w) => w.length > 1);
    for (const i of intake ?? []) {
      if (resByBooking[i.channex_booking_id]) continue;
      const rev = i.raw_revision?.attributes ?? i.raw_revision ?? {};
      const ci = rev.arrival_date, co = rev.departure_date;
      if (!ci || !co) continue;
      const cust = rev.customer ?? {};
      const nameWords = words(`${cust.name ?? ""} ${cust.surname ?? ""}`);
      const { data: cands } = await admin.from("reservations").select(resCols).eq("check_in", ci).eq("check_out", co);
      const hit = (cands ?? []).find((c: Any) => words(c.guest_name).some((w) => nameWords.includes(w)))
        ?? ((cands ?? []).length === 1 ? cands![0] : null);
      if (hit) resByBooking[i.channex_booking_id] = hit;
    }
  }

  const threads = rows.map((t) => {
    const a = t.attributes ?? {};
    const propId = t.relationships?.property?.data?.id;
    const bookingId = t.relationships?.booking?.data?.id ?? null;
    const res = bookingId ? resByBooking[bookingId] : null;
    return {
      id: t.id,
      title: a.title ?? null,
      provider: a.provider ?? null,
      last_message: typeof a.last_message === "string" ? a.last_message : a.last_message?.message ?? null,
      last_message_at: a.last_message_received_at ?? a.updated_at ?? a.inserted_at ?? null,
      unit: res?.apartments?.name ?? (propId ? unitByProp[propId] ?? null : null),
      building: res?.apartments?.buildings?.name ?? null,
      guest_name: res?.guest_name ?? null,
      check_in: res?.check_in ?? null,
      check_out: res?.check_out ?? null,
    };
  });

  const notifRows = threads.filter((t) => t.last_message_at && t.last_message).map((t) => ({
    kind: "message",
    title: `New message from ${t.guest_name ?? t.title ?? "a guest"}`,
    body: `${t.unit ? `${t.unit} · ` : ""}${String(t.last_message).slice(0, 200)}`,
    dedupe_key: `msg:${t.id}:${t.last_message_at}`,
  }));
  if (!notifRows.length) return 0;
  const { data: inserted } = await admin.from("notifications")
    .upsert(notifRows, { onConflict: "dedupe_key", ignoreDuplicates: true }).select("dedupe_key");
  const newKeys = new Set((inserted ?? []).map((r: Any) => r.dedupe_key));
  if (newKeys.size) {
    const { sendTemplateEmail } = await import("../_shared/transactional-email-templates/send-email.ts");
    for (const t of threads) {
      const key = `msg:${t.id}:${t.last_message_at}`;
      if (!newKeys.has(key)) continue;
      try {
        const lines = [
          `From: ${t.guest_name ?? t.title ?? "Guest"}`,
          `Channel: ${t.provider ?? "—"}`,
          ...(t.unit ? [`Unit: ${t.unit}${t.building ? ` (${t.building})` : ""}`] : []),
          ...(t.check_in ? [`Dates: ${t.check_in} → ${t.check_out ?? ""}`] : []),
          `Message: ${String(t.last_message)}`,
        ];
        await sendTemplateEmail("reservation-alert", "arami.vhr@gmail.com", {
          templateData: { title: `New message from ${t.guest_name ?? t.title ?? "a guest"}`, lines },
          idempotencyKey: `guest-message-${key}`,
        });
      } catch (e) {
        console.error("message alert email failed:", e);
      }
    }
  }
  return newKeys.size;
}

async function stepInspections(admin: Any) {
  const today = dubaiDate();
  const { data: tpl } = await admin.from("mobile_inspection_templates").select("id").eq("is_default", true).limit(1).maybeSingle();
  const { data: outs } = await admin.from("reservations")
    .select("id, apartment_id, guest_name, check_in, check_out, status").eq("check_out", today);
  const candidates = (outs ?? []).filter((r: Any) => String(r.status ?? "").toLowerCase() !== "cancelled");
  if (!candidates.length) return 0;
  const { data: existing } = await admin.from("mobile_inspections").select("reservation_id")
    .in("reservation_id", candidates.map((r: Any) => r.id));
  const have = new Set((existing ?? []).map((e: Any) => e.reservation_id));
  const { data: ins } = await admin.from("reservations").select("apartment_id, status").eq("check_in", today);
  const arriving = new Set((ins ?? []).filter((r: Any) => String(r.status ?? "").toLowerCase() !== "cancelled").map((r: Any) => r.apartment_id));
  const rows = candidates.filter((r: Any) => !have.has(r.id)).map((r: Any) => ({
    reservation_id: r.id,
    apartment_id: r.apartment_id,
    due_date: r.check_out,
    guest_name: r.guest_name,
    check_in: r.check_in,
    check_out: r.check_out,
    template_id: tpl?.id ?? null,
    urgent: arriving.has(r.apartment_id),
  }));
  if (!rows.length) return 0;
  const { error } = await admin.from("mobile_inspections").upsert(rows, { onConflict: "reservation_id", ignoreDuplicates: true });
  if (error) throw error;
  return rows.length;
}

type Setting = "reservation_new" | "reservation_modified" | "reservation_cancelled" | "guest_message" | "inspection_due" | "inspection_damage" | "sync_failure";
interface Item { source: string; source_id: string; setting: Setting; superOnly?: boolean; title: string; body: string; data: Record<string, unknown> }

async function stepPush(admin: Any) {
  const since = new Date(Date.now() - 24 * 3600 * 1000).toISOString();
  const items: Item[] = [];
  const aptLabel = (a: Any) => `${a?.buildings?.name ?? ""} – ${a?.name ?? ""}`;

  try {
    const { data: notifs } = await admin.from("notifications").select("id, kind, title, body, reservation_id, dedupe_key, created_at").gte("created_at", since);
    const resIds = [...new Set((notifs ?? []).filter((n: Any) => n.kind === "new" && n.reservation_id).map((n: Any) => n.reservation_id))];
    const ciById: Record<string, string> = {};
    if (resIds.length) {
      const { data: rs } = await admin.from("reservations").select("id, check_in").in("id", resIds);
      for (const r of rs ?? []) ciById[r.id] = r.check_in;
    }
    const map: Record<string, Setting> = { new: "reservation_new", modified: "reservation_modified", cancelled: "reservation_cancelled", message: "guest_message" };
    for (const n of notifs ?? []) {
      const setting = map[n.kind];
      if (!setting) continue;
      const lastMinute = n.kind === "new" && n.reservation_id && ciById[n.reservation_id] === dubaiDate(new Date(n.created_at));
      items.push({
        source: "notification", source_id: n.id, setting,
        title: `${lastMinute ? "Last Minute Reservation: " : ""}${n.title}`, body: n.body,
        data: { type: "notification", kind: n.kind, reservation_id: n.reservation_id, dedupe_key: n.dedupe_key },
      });
    }
  } catch (e) { console.error("push: notifications failed", e); }

  try {
    const { data: insp } = await admin.from("mobile_inspections").select("id, urgent, guest_name, apartments(name, buildings(name))").gte("created_at", since);
    for (const i of insp ?? []) {
      items.push({
        source: "inspection", source_id: i.id, setting: "inspection_due",
        title: i.urgent ? "Urgent inspection" : "Inspection due",
        body: `${aptLabel(i.apartments)} · guest ${i.guest_name ?? "—"} checked out`,
        data: { type: "inspection", inspection_id: i.id },
      });
    }
  } catch (e) { console.error("push: inspections failed", e); }

  try {
    const { data: dmg } = await admin.from("mobile_inspections").select("id, apartments(name, buildings(name))")
      .eq("status", "completed").eq("damage_found", true).gte("completed_at", since);
    for (const i of dmg ?? []) {
      items.push({
        source: "damage", source_id: i.id, setting: "inspection_damage", superOnly: true,
        title: "Damage found", body: aptLabel(i.apartments),
        data: { type: "inspection", inspection_id: i.id },
      });
    }
  } catch (e) { console.error("push: damage failed", e); }

  try {
    const { data: fails } = await admin.from("channex_sync_log").select("id, kind, error").not("error", "is", null).gte("created_at", since);
    for (const f of fails ?? []) {
      items.push({
        source: "sync_failure", source_id: f.id, setting: "sync_failure",
        title: "Channel sync failed", body: `${f.kind}: ${String(f.error).slice(0, 120)}`,
        data: { type: "sync_failure", sync_log_id: f.id },
      });
    }
  } catch (e) { console.error("push: sync log failed", e); }

  if (!items.length) return 0;

  // Skip already-pushed items.
  const { data: logged } = await admin.from("mobile_push_log").select("source, source_id")
    .in("source_id", items.map((i) => i.source_id));
  const done = new Set((logged ?? []).map((l: Any) => `${l.source}:${l.source_id}`));
  const fresh = items.filter((i) => !done.has(`${i.source}:${i.source_id}`));
  if (!fresh.length) return 0;

  // Recipients: admins / super admins with devices.
  const { data: roles } = await admin.from("user_roles").select("user_id, role").in("role", ["admin", "super_admin"]);
  const roleOf: Record<string, Set<string>> = {};
  for (const r of roles ?? []) (roleOf[r.user_id] ??= new Set()).add(r.role);
  const userIds = Object.keys(roleOf);
  if (!userIds.length) return 0;
  const { data: devices } = await admin.from("mobile_devices").select("user_id, expo_push_token").in("user_id", userIds);
  const { data: settings } = await admin.from("mobile_notification_settings").select("*").in("user_id", userIds);
  const settingsBy: Record<string, Any> = {};
  for (const s of settings ?? []) settingsBy[s.user_id] = s;

  // Claim each item before sending; only items we successfully claim are sent.
  const messages: Any[] = [];
  for (const it of fresh) {
    const { data: claimed, error } = await admin.from("mobile_push_log")
      .upsert({ source: it.source, source_id: it.source_id }, { onConflict: "source,source_id", ignoreDuplicates: true })
      .select("id");
    if (error || !claimed?.length) continue;
    for (const d of devices ?? []) {
      if (it.superOnly && !roleOf[d.user_id]?.has("super_admin")) continue;
      const s = settingsBy[d.user_id];
      if (s && s[it.setting] === false) continue;
      messages.push({ to: d.expo_push_token, title: it.title, body: it.body, data: it.data, sound: "default" });
    }
  }

  let sent = 0;
  for (let i = 0; i < messages.length; i += 100) {
    const batch = messages.slice(i, i + 100);
    try {
      const resp = await fetch("https://exp.host/--/api/v2/push/send", {
        method: "POST",
        headers: { "Content-Type": "application/json", Accept: "application/json" },
        body: JSON.stringify(batch),
      });
      const body = await resp.json().catch(() => null);
      const tickets: Any[] = body?.data ?? [];
      const dead: string[] = [];
      tickets.forEach((t, idx) => {
        if (t?.status === "ok") sent++;
        else if (t?.details?.error === "DeviceNotRegistered") dead.push(batch[idx].to);
      });
      if (dead.length) await admin.from("mobile_devices").delete().in("expo_push_token", dead);
    } catch (e) {
      console.error("expo push failed", e);
    }
  }
  return sent;
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  const admin = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
  const result: Record<string, unknown> = {};
  try { result.messages = await stepMessages(admin); } catch (e) { result.messages_error = String(e); }
  try { result.inspections = await stepInspections(admin); } catch (e) { result.inspections_error = String(e); }
  try { result.pushes = await stepPush(admin); } catch (e) { result.push_error = String(e); }
  return json(result);
});
