// Generated by tests/web/refresh.mjs from rent-halo-system 2fb1ffb. Do not edit.
/* eslint-disable */
// @ts-nocheck
// Pop-up and chime for new reservations that arrive from the channels.
//
// New reservations already create a "new" notification (see
// supabase/functions/_shared/channex-booking.ts). The pop-up watches for those
// and only those that came from a channel: a reservation staff created in the
// portal says "Changed in app by:", and its author doesn't need an alarm.

export interface BookingNotification {
  id: string;
  kind: string;
  title: string;
  body: string;
  reservation_id: string | null;
  created_at: string;
}

export function isChannelBooking(n: BookingNotification): boolean {
  return n.kind === "new" && !n.body.includes("Changed in app by:");
}

/** The "Label: value" lines of a notification body, keyed by label. */
export function bodyFields(body: string): Record<string, string> {
  const fields: Record<string, string> = {};
  for (const line of body.split("\n")) {
    const i = line.indexOf(":");
    if (i > 0 && !line.startsWith(" ")) fields[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return fields;
}

/**
 * Channel bookings in `latest` that aren't in `seen`, oldest first, and adds
 * them to `seen`. The first call (seen === null) only records what is already
 * there, so opening the portal doesn't replay old bookings.
 */
export function takeNewBookings(
  seen: Set<string> | null,
  latest: BookingNotification[],
): { seen: Set<string>; fresh: BookingNotification[] } {
  const channel = latest.filter(isChannelBooking);
  if (seen === null) return { seen: new Set(channel.map((n) => n.id)), fresh: [] };
  const fresh = channel.filter((n) => !seen.has(n.id));
  const next = new Set(seen);
  for (const n of fresh) next.add(n.id);
  return { seen: next, fresh: fresh.sort((a, b) => a.created_at.localeCompare(b.created_at)) };
}

