// Generated by tests/web/refresh.mjs from rent-halo-system 3ab5be3. Do not edit.
/* eslint-disable */
// @ts-nocheck
export type UserType = "super_admin" | "admin" | "owner";
export function diffReservation(before: Reservation | undefined, updates: Partial<Reservation>): string[] {
  if (!before) return [];
  const labels: [keyof Reservation, string][] = [
    ["guest_name", "Guest"],
    ["apartment_id", "Apartment"],
    ["check_in", "Check-in"],
    ["check_out", "Check-out"],
    ["status", "Status"],
    ["total_price", "Total amount"],
    ["adults", "Adults"],
    ["children", "Children"],
    ["infants", "Infants"],
    ["guest_phone", "Phone"],
    ["guest_email", "Email"],
    ["notes", "Notes"],
  ];
  const out: string[] = [];
  for (const [key, label] of labels) {
    if (!(key in updates)) continue;
    const b = before[key] == null || before[key] === "" ? "—" : String(before[key]);
    const a = updates[key] == null || updates[key] === "" ? "—" : String(updates[key]);
    if (b !== a) out.push(`${label}: ${b} → ${a}`);
  }
  return out;
}

export function getOverlappingReservations(
  reservations: Reservation[],
  apartmentId: string,
  checkIn: string,
  checkOut: string,
  excludeId?: string
): Reservation[] {
  return reservations.filter(
    (r) =>
      r.apartment_id === apartmentId &&
      r.status !== "cancelled" &&
      r.id !== excludeId &&
      r.check_in < checkOut &&
      r.check_out > checkIn
  );
}

export const PAGE_ACCESS: Record<string, UserType[]> = {
  "/pricing": ["super_admin"],
  "/users": ["super_admin"],
  "/apartment-finance": ["super_admin"],
  "/channel-manager": ["super_admin"],
  "/financial": ["super_admin", "owner"],
  "/buildings": ["super_admin", "admin"],
  "/tasks": ["super_admin", "admin"],
  "/notifications": ["super_admin", "admin"],
  "/messages": ["super_admin", "admin"],
  "/messages/automation": ["super_admin", "admin"],
};

export function canAccessPage(type: UserType | undefined, path: string) {
  const allowed = PAGE_ACCESS[path];
  if (!allowed) return true;
  return !!type && allowed.includes(type);
}

export function webLoginEmail(email: string) {
  const identifier = email.toLowerCase().trim();
  const finalEmail = identifier.includes("@") ? identifier : `${identifier}@arami.app`;
  return finalEmail;
}

export function webUserType(data: { role: string }[] | null) {
  const roles = (data || []).map((r: any) => r.role);
  if (roles.includes("super_admin")) return "super_admin";
  if (roles.includes("admin")) return "admin";
  return "owner";
}
