// Copies the website's logic the app must match into tests/web/*.ts, so the
// tests compare the app against the live website code (read-only; nothing is
// written to the website repo).
//   node tests/web/refresh.mjs /path/to/rent-halo-system [ref]
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const [repo, ref = "origin/main"] = process.argv.slice(2);
if (!repo) throw new Error("usage: node tests/web/refresh.mjs <rent-halo-system path> [ref]");
const show = (p) => execFileSync("git", ["-C", repo, "show", `${ref}:${p}`], { encoding: "utf8" });
const commit = execFileSync("git", ["-C", repo, "rev-parse", "--short", ref], { encoding: "utf8" }).trim();

/** Source of a top-level declaration starting at `start`, by brace matching. */
function take(src, start) {
  const i = src.indexOf(start);
  if (i < 0) throw new Error(`not found: ${start}`);
  let depth = 0, seen = false;
  for (let j = i; j < src.length; j++) {
    if (src[j] === "{") { depth++; seen = true; }
    if (src[j] === "}") { depth--; if (seen && depth === 0) return src.slice(i, j + 1 + (src[j + 1] === ";" ? 1 : 0)); }
  }
  throw new Error(`unbalanced: ${start}`);
}

const header = `// Generated by tests/web/refresh.mjs from rent-halo-system ${commit}. Do not edit.\n/* eslint-disable */\n// @ts-nocheck\n`;
const data = show("src/hooks/use-data.ts");
const users = show("src/hooks/use-users.ts");
const login = show("src/pages/Login.tsx");
const loginLine = login.split("\n").find((l) => l.includes("@arami.app"));
const roleFn = users.slice(users.indexOf("const roles = "), users.indexOf('return "owner";') + 'return "owner";'.length);

writeFileSync(
  "tests/web/oracle.ts",
  header +
    `export type UserType = "super_admin" | "admin" | "owner";\n` +
    "export " + take(data, "function diffReservation(") + "\n\n" +
    take(data, "export function getOverlappingReservations(") + "\n\n" +
    "export " + take(users, "const PAGE_ACCESS") + "\n\n" +
    take(users, "export function canAccessPage(") + "\n\n" +
    `export function webLoginEmail(email: string) {\n  const identifier = email.toLowerCase().trim();\n  ${loginLine.trim()}\n  return finalEmail;\n}\n\n` +
    `export function webUserType(data: { role: string }[] | null) {\n  ${roleFn.replace(/\n\s*/g, "\n  ")}\n}\n`,
);
writeFileSync("tests/web/mobile-push-dispatch.ts", header + show("supabase/functions/mobile-push-dispatch/index.ts"));
writeFileSync("tests/web/mobile-inspection-complete.ts", header + show("supabase/functions/mobile-inspection-complete/index.ts"));
console.log("web oracle refreshed from", commit);
