// Copies the website's logic the app must match into tests/web/*.ts, so the
// tests compare the app against the live website code (read-only; nothing is
// written to the website repo).
//   node tests/web/refresh.mjs /path/to/rent-halo-system [ref]
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const [repo, ref = "origin/main"] = process.argv.slice(2);
if (!repo) throw new Error("usage: node tests/web/refresh.mjs <rent-halo-system path> [ref]");
const show = (p) => execFileSync("git", ["-C", repo, "show", `${ref}:${p}`], { encoding: "utf8" });
const commit = execFileSync("git", ["-C", repo, "rev-parse", "--short", ref], { encoding: "utf8" }).trim();

/** Source of a top-level declaration starting at `start`, by brace matching. */
function take(src, start) {
  const i = src.indexOf(start);
  if (i < 0) throw new Error(`not found: ${start}`);
  let depth = 0, seen = false;
  for (let j = i; j < src.length; j++) {
    if (src[j] === "{") { depth++; seen = true; }
    if (src[j] === "}") { depth--; if (seen && depth === 0) return src.slice(i, j + 1 + (src[j + 1] === ";" ? 1 : 0)); }
  }
  throw new Error(`unbalanced: ${start}`);
}

/** A top-level function by its closing brace at column 0 (safe with object return types). */
function takeBlock(src, start) {
  const i = src.indexOf(start);
  if (i < 0) throw new Error(`not found: ${start}`);
  const j = src.indexOf("\n}\n", i);
  return src.slice(i, j + 2);
}

const header = `// Generated by tests/web/refresh.mjs from rent-halo-system ${commit}. Do not edit.\n/* eslint-disable */\n// @ts-nocheck\n`;
const data = show("src/hooks/use-data.ts");
const users = show("src/hooks/use-users.ts");
const login = show("src/pages/Login.tsx");
const loginLine = login.split("\n").find((l) => l.includes("@arami.app"));
const roleFn = users.slice(users.indexOf("const roles = "), users.indexOf('return "owner";') + 'return "owner";'.length);

writeFileSync(
  "tests/web/oracle.ts",
  header +
    `export type UserType = "super_admin" | "admin" | "owner";\n` +
    "export " + take(data, "function diffReservation(") + "\n\n" +
    take(data, "export function getOverlappingReservations(") + "\n\n" +
    "export " + take(users, "const PAGE_ACCESS") + "\n\n" +
    take(users, "export function canAccessPage(") + "\n\n" +
    `export function webLoginEmail(email: string) {\n  const identifier = email.toLowerCase().trim();\n  ${loginLine.trim()}\n  return finalEmail;\n}\n\n` +
    `export function webUserType(data: { role: string }[] | null) {\n  ${roleFn.replace(/\n\s*/g, "\n  ")}\n}\n`,
);
const fin = show("src/pages/Financial.tsx");
const bodyStart = fin.indexOf("const results = useMemo(() => {") + "const results = useMemo(() => {".length;
const bodyEnd = fin.indexOf("}, [", bodyStart);
const finBody = fin.slice(bodyStart, bodyEnd).replace(/\n\s*\/\/ eslint-disable-next-line[^\n]*\n\s*$/, "\n");
writeFileSync(
  "tests/web/financial.ts",
  header +
    `import { format, differenceInDays, max as dateMax, min as dateMin } from "date-fns";\n\n` +
    takeBlock(fin, "function computeProRatedAmount(") + "\n\n" +
    `/** The website Financial page's numbers, with its component state passed in. */\n` +
    `export function webFinancial({ reservations, apartments, financeRows, selectedApartments, manageFilter, startDate, endDate }) {\n` +
    `  const isAllSelected = selectedApartments.length === 0;\n` +
    `  const scopedApartments = manageFilter === "all" ? apartments : apartments.filter((a) => a.manage_type === manageFilter);\n` +
    `  const scopedIdSet = new Set(scopedApartments.map((a) => a.id));\n` +
    finBody + "}\n",
);
writeFileSync("tests/web/mobile-push-dispatch.ts", header + show("supabase/functions/mobile-push-dispatch/index.ts"));
writeFileSync("tests/web/mobile-inspection-complete.ts", header + show("supabase/functions/mobile-inspection-complete/index.ts"));
console.log("web oracle refreshed from", commit);
const guestFields = show("src/components/GuestCountFields.tsx");
writeFileSync("tests/web/guests.ts", header + take(guestFields, "export function guestCountsPayload") + "\n");
writeFileSync("tests/web/overbookings.ts", header + show("src/lib/overbookings.ts"));
const nba = show("src/lib/new-booking-alert.ts");
writeFileSync("tests/web/new-booking-alert.ts", header + nba.slice(0, nba.indexOf("// ---- Sound ----")));
const msgApi = show("src/lib/messages-api.ts");
writeFileSync(
  "tests/web/messages-api.ts",
  header + msgApi.slice(msgApi.indexOf("export interface Thread"), msgApi.indexOf("export interface Msg")) + msgApi.slice(msgApi.indexOf("const words =")),
);
writeFileSync("tests/web/sync-alert-core.ts", header + show("supabase/functions/_shared/sync-alert-core.ts"));
