// Generated by tests/web/refresh.mjs from rent-halo-system faf3f1f. Do not edit.
/* eslint-disable */
// @ts-nocheck
// The runtime-free part of _shared/sync-alerts.ts, kept separate so the unit
// tests can import it without Deno or the email templates.

export interface SyncAlert {
  /** Identifies the issue, e.g. "no-unit:BookingCom:5228929505". */
  key: string;
  title: string;
  lines: string[];
  reservationId?: string | null;
}

export type SendAlertEmail = (alert: SyncAlert, dedupeKey: string) => Promise<void>;

/** Today's date in Dubai as YYYY-MM-DD. */
export function dubaiDay(now: Date = new Date()): string {
  return new Date(now.getTime() + 4 * 60 * 60 * 1000).toISOString().slice(0, 10);
}

/** The notifications.dedupe_key for an issue: one per issue per Dubai day. */
export function alertDedupeKey(key: string, now: Date = new Date()): string {
  return `alert:${key}:${dubaiDay(now)}`;
}

/**
 * Records the alert in notifications and emails it, unless the same issue was
 * already alerted today. Never throws: an alert failing must not stop the sync
 * work that raised it. Returns true when a new alert went out.
 */
// deno-lint-ignore no-explicit-any
export async function recordSyncAlert(admin: any, alert: SyncAlert, sendEmail: SendAlertEmail, now: Date = new Date()) {
  const dedupeKey = alertDedupeKey(alert.key, now);
  try {
    // notifications has a unique index on dedupe_key, so a second insert for
    // the same issue on the same day fails with 23505 and nothing is sent.
    const { error } = await admin.from("notifications").insert({
      kind: "alert",
      title: alert.title,
      body: alert.lines.join("\n"),
      reservation_id: alert.reservationId ?? null,
      dedupe_key: dedupeKey,
    });
    if (error) {
      if (error.code !== "23505") console.error("sync alert notification failed:", error.message);
      return false;
    }
  } catch (e) {
    console.error("sync alert notification failed:", e);
    return false;
  }

  try {
    await sendEmail(alert, dedupeKey);
  } catch (e) {
    console.error("sync alert email failed (notification was saved):", e);
  }
  return true;
}
